spring:
  application:
    name: FireCheck_1.0
  profiles:
    active: test
  thymeleaf:
    prefix: /WEB-INF/views/
    suffix: .html
    cache: false

  messages:
    basename: classpath:/message/messages
    cache-duration: 5
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  jmx:
    enabled: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://{DEV-WIN_DB_URI}
    username: {DEV-WIN_ID}
    password: {DEV-WIN_PASSWORD}
    mapper-locations: classpath:/database/mapper/**/*.xml
mybatis:
  config-location: classpath:/database/mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: NULL
server:
  address: localhost #  adress를 지정하지 않으면 spring.boot.admin에서 host네임을 이용하여 접근하여 정상적으로 서비스가 안 됨. 때문에 address를 지정해야 함
  port: 8080
  #  max-http-header-size: 30000
  max-http-request-header-size: 30000
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 86400
    jsp:
      init-parameters:
        development: true
info:
  version: 1.0
  groupId: hans.firefighting
  artifactId: check
  title: facility_check

logging:
  level:
    jdbc:
      sqlonly: off
      sqltiming: info
      resultsettable: info
      audit: off
      resultset: off
      connection: off

jasypt:
  encryptor:
    bean: jasyptEncryptorAES

file_upload:
  fileupload:
    location: {FILE_UPLOAD_LOCATION}
    allowedExtensions: [hwp, doc, docx, ppt, pptx, xls, xlsx, jpg, jpeg, gif, bmp, png, txt, zip, pdf]
    maxFileSize: 10MB
  user:
    passwordErrorLimit: 5
  encrypt:
    key: {ENCRYPTION_KEY}
    alg: "AES/CBC/PKCS5Padding"